# Generated by Django 4.0.1 on 2022-01-22 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_usercategory_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategory',
            new_name='UserCategorySub',
        ),
    ]
