# Generated by Django 4.0.2 on 2022-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_usercategory_usercategorysub'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text_en',
            field=models.TextField(null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_ru',
            field=models.TextField(null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
    ]
