# Generated by Django 4.0.2 on 2022-02-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
