# Generated by Django 4.0.2 on 2022-02-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.comment', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
