# Generated by Django 4.0.2 on 2022-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_comment_email_comment_parent_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=555),
        ),
    ]
