# Generated by Django 4.0.2 on 2022-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
